export const customSelectStyles = {
  control: (provided, state) => ({
    ...provided,
    display: "flex",
    alignItems: "center",
    fontSize: "1.4rem",
    padding: "0 1.2rem",
    border: `1px solid var(--color-grey-300)`,
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomLeftRadius: "0",
    borderBottomRightRadius: "0",
    backgroundColor: "var(--color-grey-0)",
    fontWeight: 500,
    boxShadow: "var(--shadow-sm)",
    minHeight: "3.1rem",
    height: "3.1rem",
    ...(state.isFocused && {
      borderColor: "var(--color-green-500)",
      boxShadow: "0 0 0 1px var(--color-green-500)",
    }),
  }),
  singleValue: (provided) => ({
    ...provided,
    color: "var(--color-grey-900)",
    fontSize: "1.4rem",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    height: "100%", // <-- ensures vertical centering
    margin: 0,
    padding: 0,
  }),
  input: (provided) => ({
    ...provided,
    color: "var(--color-grey-900)",
    fontSize: "1.4rem",
    fontWeight: 500,
    margin: 0,
    padding: 0,
    display: "flex",
    alignItems: "center",
    height: "100%",
  }),
  menu: (provided) => ({
    ...provided,
    backgroundColor: "var(--color-grey-0)",
    color: "var(--color-grey-900)",
    fontSize: "1.4rem",
    fontWeight: 500,
    zIndex: 100,
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isFocused
      ? "var(--color-grey-100)"
      : "var(--color-grey-0)",
    color: "var(--color-grey-900)",
    fontSize: "1.4rem",
    fontWeight: 500,
    cursor: "pointer",
    minHeight: "2.4rem",
    paddingTop: "0.2rem",
    paddingBottom: "0.2rem",
  }),
  placeholder: (provided) => ({
    ...provided,
    color: "var(--color-grey-500)",
    fontSize: "1.4rem",
    fontWeight: 500,
    display: "flex",
    alignItems: "center",
    height: "100%",
  }),
  indicatorSeparator: () => ({
    display: "none",
  }),
  dropdownIndicator: (provided) => ({
    ...provided,
    color: "var(--color-grey-500)",
    padding: "0 0.4rem",
    display: "flex",
    alignItems: "center",
    height: "100%",
  }),
};
